baseURL = "https://business.epsilondelta.ai/"
languageCode = "en-us"
title = "Mediumish"
enableRobotsTXT = true
enableEmoji = true

# Pagination
[pagination]
  pagerSize = 6

[params]
  name = "Mediumish"
  description = "Jekyll template, Medium styled, free for bloggers."
  logo = "images/logo.png"
  favicon = "images/logo.png"
  
  # External Services
  googleAnalytics = "UA-46278016-1"
  disqus = "demowebsite"
  mailchimpList = "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
  
  # Features
  lazyImages = "disabled"
  adsense = "disabled"
  adsenseDataAdClient = "ca-pub-3412143450191416"
  adsenseDataAdSlot = "1363087678"

# Authors configuration
[params.authors]
  [params.authors.sal]
    name = "Sal"
    display_name = "Sal"
    gravatar = "e56154546cf4be74e393c62d1ae9f9d4"
    email = "wowthemesnet@gmail.com"
    web = "https://www.wowthemes.net"
    twitter = "https://twitter.com/wowthemesnet"
    description = "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  
  [params.authors.john]
    name = "John"
    display_name = "John"
    avatar = "images/avatar.png"
    gravatar = "b1cc14991db7a456fcd761680bbc8f81"
    email = "wowthemesnet@gmail.com"
    web = "https://www.wowthemes.net"
    twitter = "https://twitter.com/wowthemesnet"
    description = "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Permalinks
[permalinks]
  posts = "/:title/"

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"

# Outputs
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4

# Menu
[[menu.main]]
  name = "Blog"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2

