baseURL = "https://business.epsilondelta.ai/"
languageCode = "ko-kr"
title = "엡실론델타의 시시콜콜 비즈니스"
enableRobotsTXT = true
enableEmoji = true

# Pagination
[pagination]
  pagerSize = 6

[params]
  name = "시시콜콜 비즈니스"
  description = "엡실론델타가 비즈니스를 만들기 위한 모든 사소하지만 소중한 이야기"
  logo = "images/epsilondelta_symbol_v3.png"
  favicon = "images/epsilondelta_symbol_v3.png"
  company = "주식회사 엡실론델타"
  
  # External Services
  googleAnalytics = "G-XSNXBDSF2E"
  disqus = "business-epsilondelta"
  mailchimpList = "https://epsilondelta.us13.list-manage.com/subscribe/post?u=caa16af6fb5c7e40657e9e844&amp;id=7496bda80a&amp;f_id=0040f4e1f0"
  
  # Features
  lazyImages = "disabled"
  adsense = "disabled"
  adsenseDataAdClient = "ca-pub-3412143450191416"
  adsenseDataAdSlot = "1363087678"

# Permalinks
[permalinks]
  posts = "/:title/"

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

# Outputs
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4

# Menu
[[menu.main]]
  name = "Blog"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Authors"
  url = "/authors"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 3

